### ISSUE TITLE
@0x/contracts-gen copy issue

### ISSUE THREAD

**Issue by gabririgo** [0xProject/tools#14] opened 2020-12-11 12:42 UTC
## Expected Behavior

"@0x/contracts-gen copy" should pull the contracts list from compiler.json file, when specified, and correctly pop the .sol extension at the end of the file name

## Current Behavior

Returns the following error (Migrations.sol is the first contract in the compiler.json contracts list) when running "contracts-gen copy"
"
> contracts-gen copy

{ Error: ENOENT: no such file or directory, copyfile './test/generated-artifacts/Migrations.sol.json' -> './generated-artifacts/Migrations.sol.json'
"

## Steps to Reproduce (for bugs)

```
1. Add a list of contract names (even without .sol extension, sol-compiler will overwrite it with ${name}.sol)
2. run script "sol-compiler copy"

```

## Your Environment

| Package | Version |
| @0x/sol-compiler: | :4.4.1 |

| Network |
| ------- |
| testrpc |

**Comment by gabririgo** [comment] 2021-01-11 12:08
hey @abandeali1 I think this issue went unnoticed. Can you please advise whether it is something you'll be looking to fix, before it is automatically closed?

**Comment by mzhu25** [comment] 2021-01-12 00:24
@gabririgo Can you confirm that `./test/generated-artifacts/Migrations.sol.json` exists before `contracts-gen copy` is run? Looks like the problem is `contracts-gen copy` can't find the artifacts; maybe `contracts-gen generate` is outputting them somewhere unexpected

**Comment by gabririgo** [comment] 2021-01-14 18:58
> @gabririgo Can you confirm that `./test/generated-artifacts/Migrations.sol.json` exists before `contracts-gen copy` is run? Looks like the problem is `contracts-gen copy` can't find the artifacts; maybe `contracts-gen generate` is outputting them somewhere unexpected

I can confirm ./test/generated-artifacts/Migrations.sol.json does not exist, as the generated artifacts are ./test/generated-artifacts/Migrations.json and ./test/generated-artifacts/Migrations.input.json instead.

Can you please confirm the issue is isolated to me and you can execute contracts-gen copy correctly when specifying the contract(s) to be compiled in the compiler.json file?

**Comment by mzhu25** [comment] 2021-01-15 01:38
Ah, sorry –– I misunderstood your original post. Fixed in the above PR.

**Closed** 2021-01-15 03:03 UTC

**Comment by mzhu25** [comment] 2021-01-15 03:52
Published https://www.npmjs.com/package/@0x/contracts-gen

**Comment by gabririgo** [comment] 2021-01-15 11:02
> Ah, sorry –– I misunderstood your original post. Fixed in the above PR.

thank for quick fix, already upgraded packages and can confirm everything worked smoothly.
